# Source: skylark/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: skylark-webhooks
  namespace: openaios
  labels:
    helm.sh/chart: skylark-0.7.0
    app.kubernetes.io/name: skylark
    app.kubernetes.io/instance: skylark
    app.kubernetes.io/version: "0.7.0"
spec:
  type: ClusterIP
  ports:
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: tls
  selector:
    app.kubernetes.io/name: skylark
    app.kubernetes.io/instance: skylark
